version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "4000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: sh -c "npm install && npm start"