version: '3.8'

services:
  frontend:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "4000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: sh -c "npm install --legacy-peer-deps && npm start"